Resources:
  SCUUIDTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.SCUUID_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: scUUID
          AttributeType: S
      KeySchema:
        - AttributeName: scUUID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST